spring:
  datasource:
    url: jdbc:h2:file:/data/cdrdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: CDR
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: quest
    password: quest

call-simulator:
  thread-pool-size: 10
  batch-size: 1000

rabbitmq:
  exchange: call_exchange
  queue: call_queue
  routing-key: call.routing.key
