spring:
  application:
    name: CRM
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.crm.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://postgres-crm:5432/crm-database
    driver-class-name: org.postgresql.Driver
    username: crm_admin
    password: crm_admin

brt:
  clients-base-url: http://brt-service:8081/v1/clients

admin:
  username: admin
  password: admin

server:
  port: 8083
